package com.grselectronics.inventario.bean;
// Generated 23-jun-2016 15:07:51 by Hibernate Tools 4.3.1



/**
 * AsignacionEquipo generated by hbm2java
 */
public class AsignacionEquipo  implements java.io.Serializable {


     private Integer idAsignacionEquipo;
     private Empleado empleado;
     private Equipo equipo;
     private Usuario usuario;
     private String fechaDesde;
     private String fechaHasta;

    public AsignacionEquipo() {
    }

    public AsignacionEquipo(Empleado empleado, Equipo equipo, Usuario usuario, String fechaDesde, String fechaHasta) {
       this.empleado = empleado;
       this.equipo = equipo;
       this.usuario = usuario;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
    }
   
    public Integer getIdAsignacionEquipo() {
        return this.idAsignacionEquipo;
    }
    
    public void setIdAsignacionEquipo(Integer idAsignacionEquipo) {
        this.idAsignacionEquipo = idAsignacionEquipo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(String fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    public String getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(String fechaHasta) {
        this.fechaHasta = fechaHasta;
    }




}


